- name: Test Internet to Web server
  connection: local
  hosts: localhost
  tasks:
    - name: Take new snapshot
      forward_snapshot:
        freshness: "{{ freshness }}"
        type: collect
        wait_time: 120
        devices:
          - n9k01
      register: result
    - name: Print snapshot link
      debug:
        msg: '{{ result.snapshot_link }}'
